### ISSUE TITLE
How to send multi-line flomo content

### ISSUE THREAD

**Issue by featureswag** [Mayandev/flomo-cli#1]
i cant send it

**Comment by Mayandev** [comment]
> i cant send it

can you provide any error message or screenshot?

**Comment by featureswag** [comment]
I don't think is an error. I just don't know how to sent it, always in typing😅😅😅

**Comment by Mayandev** [comment]
> I don't think is an error. I just don't know how to sent it, always in typing😅😅😅

1. command: `flomo edit`
2. input `i` for insert content
3. input your content
4. press `esc` then input `:wq`

This is work for me(MacOS).

BTW, this is some basic [vim edit trick](https://www.radford.edu/~mhtay/CPSC120/VIM_Editor_Commands.htm).

**Comment by featureswag** [comment]
Thanks！！

**Comment by APPTOOSTILL** [comment]
/usr/local/lib/node_modules/flomo-cli/node_modules/ora/index.js:401
		} catch {
		        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/flomo-cli/bin/main.js:7:13)
大佬，想问一下这是什么情况，
